@startuml
'https://plantuml.com/class-diagram


folderOptions <|-- Base43
website <|-- Base43
class Base43 {
getWebsiteName();
getAuthorName();
useJavascriptFiles();
useCSSFiles();
folderOptions
outputToFile();
outputToConsole();
printConsoleOutput();
}
class folderOptions{
    willCreateFolder();
}

class website{
    fillFile();
    createFolders();
}
@enduml